GET http://localhost:3003/api/blogs

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "Prueba",
    "author": "David",
    "url": "http://someone.url",
    "likes": 123
}

###
POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "root",
    "password": "toor"
}

###
POST http://localhost:3003/api/login
content-type: application/json

{
    "username": "root",
    "password": "toor"
}

###
POST http://localhost:3003/api/blogs 
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY2ODY4Yjc3YTZmYWQ5NWEwMDU4ZWQ3YyIsImlhdCI6MTcyMDA5NDQ2MiwiZXhwIjoxNzIwNjk5MjYyfQ.SP0cSvo3aw8VvMH4xcSkzLUdHGyZOJvxJYNr7fU0lC8

{
    "title": "Blog 3",
    "author": "David",
    "url": "http://someone.url",
    "likes": 123
}
