GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "Prueba",
    "author": "David",
    "url": "http://someone.url",
    "likes": 123
}

###
POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "sapo",
    "password": ""
}

###
POST http://localhost:3003/api/login
content-type: application/json

{
    "username": "sapo",
    "password": "con"
}

###
POST http://localhost:3003/api/blogs 
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9zdXMiLCJpZCI6IjVhNDIyYTg1MWI1NGE2NzYyMzRkMTdmOCIsImlhdCI6MTcxOTIyNjcxMn0.i794s0FbH3ujOvLhE3OkDEhTRkouVLUsCCb34vA5nKQ

{
    "title": "Prueba2",
    "author": "David",
    "url": "http://someone.url",
    "likes": 123
}
